/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_preferences_window (void);
GtkWidget* create_site_window (void);
GtkWidget* create_tank_window (void);
GtkWidget* create_plugins_window (void);
GtkWidget* create_statistics_window (void);
GtkWidget* create_renumber_window (void);
